sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    database: 10
    host: localhost
    port: 6379
    password: 123456
  wechat:
    appid: wx7a1832e4de5550a3
    secret: bb4b405a98548a1de3304c28caabeb26